Book Reference: page 123-165 of **Python for Data Analysis Book by Wes McKinney**

# pandas

- contains data structures and data manipulation tools designed to make data cleaning and analysis fast and easy in Python
- Difference between pandas and numpy:
    - pandas is designed for working with tabular or heterogeneous data
    - Numpy is best suited for working with homogeneous numerical array data
- open source project in 2010

In [1]:
import pandas as pd

# or 
# from pandas import Series, DataFrame

### 2 Workhorse data structures
1. Series
    - is a one-dimensional array-like object containing a sequence of values and an associated array of data labels (index)
    - fixed-length, ordered dict
2. DataFrame
    - represents a rectangular table of data
    - contains an ordered collection of columns (which may be of different value types)
    - has both a row and column index
    - dict of Series sharing the same index

In [2]:
obj = pd.Series([1,2,3,'ha'])
obj

0     1
1     2
2     3
3    ha
dtype: object

In [3]:
obj2 = pd.Series([4, 7, -5, 3])
obj2

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj2.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [8]:
# use labels in the index when selecting single values or a set of values
obj2['a']

-5

In [9]:
obj2['d'] = 6

In [10]:
obj2[['c', 'a', 'd']] #c,a,d interpreted as list of indices

c    3
a   -5
d    6
dtype: int64

Numpy-like operations
- filtering with a boolean arra
- scalar multiplication
- applying math functions

In [11]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [12]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [13]:
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [14]:
# dict-like operations
'b' in obj2

True

In [15]:
# convert Python dict to Series

sdata = {'Ohio': 35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [16]:
# override ordered index through...
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [17]:
# Check for missing or NA 
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [18]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [19]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [20]:
# Data alignment feature
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Series' object itself AND Series' index both have names


In [21]:
obj4.name = 'population'

In [22]:
obj4.index.name = 'state'

In [23]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [24]:
obj

0     1
1     2
2     3
3    ha
dtype: object

In [25]:
# Series's index can be altered in-place by assignment
obj.index = ['Jennie', 'Lisa', 'Rose', 'Jisoo']

In [26]:
obj

Jennie     1
Lisa       2
Rose       3
Jisoo     ha
dtype: object

### DataFrame

In [27]:
data = {
    'singer': ['Blackpink', 'NCT', 'Seventeen', 'SF9'],
    'year': [2018, 2017, 2019, 2017],
    'title': ['As If It\'s Your Last', 'Cherry Bomb', 'Fear', 'O Sole Mio']
}

In [28]:
frame = pd.DataFrame(data)

In [29]:
frame

singer                 title  year
0  Blackpink  As If It's Your Last  2018
1        NCT           Cherry Bomb  2017
2  Seventeen                  Fear  2019
3        SF9            O Sole Mio  2017

In [30]:
frame.head() # displays first five rows

singer                 title  year
0  Blackpink  As If It's Your Last  2018
1        NCT           Cherry Bomb  2017
2  Seventeen                  Fear  2019
3        SF9            O Sole Mio  2017

In [31]:
pd.DataFrame(data, columns=['year', 'title', 'singer'])

year                 title     singer
0  2018  As If It's Your Last  Blackpink
1  2017           Cherry Bomb        NCT
2  2019                  Fear  Seventeen
3  2017            O Sole Mio        SF9

In [32]:
frame2 = pd.DataFrame(data, columns=['year', 'title', 'singer', 'rating'], 
            index=['one', 'two', 'three', 'four'])
frame2

year                 title     singer rating
one    2018  As If It's Your Last  Blackpink    NaN
two    2017           Cherry Bomb        NCT    NaN
three  2019                  Fear  Seventeen    NaN
four   2017            O Sole Mio        SF9    NaN

In [33]:
frame2.columns

Index(['year', 'title', 'singer', 'rating'], dtype='object')

In [34]:
frame2['singer']

one      Blackpink
two            NCT
three    Seventeen
four           SF9
Name: singer, dtype: object

In [35]:
frame2.title # this only works when the column name is a valid Python variable name

one      As If It's Your Last
two               Cherry Bomb
three                    Fear
four               O Sole Mio
Name: title, dtype: object

In [36]:
frame2.loc['three'] #rows

year           2019
title          Fear
singer    Seventeen
rating          NaN
Name: three, dtype: object

Columns can be modified by assignment

In [37]:
frame2['rating'] = 3.5

In [38]:
frame2

year                 title     singer  rating
one    2018  As If It's Your Last  Blackpink     3.5
two    2017           Cherry Bomb        NCT     3.5
three  2019                  Fear  Seventeen     3.5
four   2017            O Sole Mio        SF9     3.5

In [39]:
frame2['rating'] = np.arange(4.)

In [40]:
frame2

year                 title     singer  rating
one    2018  As If It's Your Last  Blackpink     0.0
two    2017           Cherry Bomb        NCT     1.0
three  2019                  Fear  Seventeen     2.0
four   2017            O Sole Mio        SF9     3.0

In [41]:
# Series(rating_value's) length must match the length of  the DataFrame
rating_val = pd.Series([4,5], index=['two', 'four'])

In [42]:
frame2['rating'] = rating_val

In [43]:
frame2

year                 title     singer  rating
one    2018  As If It's Your Last  Blackpink     NaN
two    2017           Cherry Bomb        NCT     4.0
three  2019                  Fear  Seventeen     NaN
four   2017            O Sole Mio        SF9     5.0

In [44]:
# add new column
frame2['girl_group'] = frame2.singer == 'Blackpink'

In [45]:
frame2

year                 title     singer  rating  girl_group
one    2018  As If It's Your Last  Blackpink     NaN        True
two    2017           Cherry Bomb        NCT     4.0       False
three  2019                  Fear  Seventeen     NaN       False
four   2017            O Sole Mio        SF9     5.0       False

In [46]:
# delete column
del frame2['girl_group']

In [47]:
frame2

year                 title     singer  rating
one    2018  As If It's Your Last  Blackpink     NaN
two    2017           Cherry Bomb        NCT     4.0
three  2019                  Fear  Seventeen     NaN
four   2017            O Sole Mio        SF9     5.0

In [48]:
frame2.columns

Index(['year', 'title', 'singer', 'rating'], dtype='object')

The column returned from indexing a DataFrame is a view on the
underlying data, not a copy. Thus, any in-place modifications to the
Series will be reflected in the DataFrame. The column can be
explicitly copied with the Series’s **copy method**.

In [49]:
# nested dict of dicts
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [50]:
frame3 = pd.DataFrame(pop)

In [51]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [52]:
frame3.T # transpose

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [53]:
frame3['Ohio'][:-1]

2000    1.5
2001    1.7
Name: Ohio, dtype: float64

In [54]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [55]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [56]:
frame2.values # see how dtype is object

array([[2018, "As If It's Your Last", 'Blackpink', nan],
       [2017, 'Cherry Bomb', 'NCT', 4.0],
       [2019, 'Fear', 'Seventeen', nan],
       [2017, 'O Sole Mio', 'SF9', 5.0]], dtype=object)

### Index Objects
    - responsible for holding the axis labels and other metadata
    - immutable
    - fixed-size set
    - can contain duplicate labels

In [57]:
obj = pd.Series(range(3), index=['a','b','c'])
obj

a    0
b    1
c    2
dtype: int64

In [58]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [59]:
index[1:]

Index(['b', 'c'], dtype='object')

In [60]:
# immutable index
index[1] = 'd'

TypeError: Index does not support mutable operations

In [61]:
labels = pd.Index(np.arange(3))

In [62]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [63]:
# Immutability makes it safer to share Index objects among data structures
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [64]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [65]:
obj2.index is labels

True

In [66]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [67]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [68]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [69]:
# duplicate labels
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [70]:
# rename index/column through rename func
frame3.rename(columns={'Nevada':'the nevada'}, inplace=True)

In [71]:
frame3.columns

Index(['the nevada', 'Ohio'], dtype='object', name='state')

### Reindexing
    -An important method on pandas objects is reindex, which means to create a new object with the data conformed to a new index.
    - require that the labels be unique

In [72]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [73]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [74]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [75]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

For ordered data like **time series**, it may be desirable to do some **interpolation or filling of values** when reindexing. The method option allows us to do this, using a method such as ffill, which forward-fills the values

In [76]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [77]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [78]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

With DataFrame, reindex can alter either the (row) index, columns, or both. When
passed only a sequence, it reindexes the rows in the result:

In [79]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
     index=['a', 'c', 'd'],
     columns=['Ohio', 'Texas', 'California'])

In [80]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [81]:
# reindex rows
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [82]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [83]:
# reindex columns
states = ['Texas', 'Utah', 'California']
frame.reindex(columns= states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [84]:
frame.reindex(index=['a', 'b', 'c', 'd'], columns=states)
# see more reindex function arguments to customize

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [85]:
frame2.columns

Index(['Ohio', 'Texas', 'California'], dtype='object')

In [86]:
frame.reindex(columns=['Texas','Utah','California'], fill_value=0)

Texas  Utah  California
a      1     0           2
c      4     0           5
d      7     0           8

In [87]:
# Dropping Entries from an Axis

In [88]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [89]:
new_obj = obj.drop('c')

In [90]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [91]:
obj.drop(['d', 'c']) 
# drop method will return a new object with the 
# indicated value or values deleted from an axis:

a    0.0
b    1.0
e    4.0
dtype: float64

In [92]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
     index=['Ohio', 'Colorado', 'Utah', 'New York'],
     columns=['one', 'two', 'three', 'four'])

In [93]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [94]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [95]:
# drop values from the columns by passing axis=1 or axis='columns':
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [96]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [97]:
# You can also choose to modify the size or shape of a Series or DataFrame using
# in-place

obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

Be careful with the inplace, as it <span style="color:red">destroys any data that is dropped. </span>

### Indexing, Selection, and Filtering

In [98]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [99]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [100]:
obj['b']

1.0

In [101]:
obj[1]

1.0

In [102]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [103]:
obj['b':'d']

b    1.0
c    2.0
d    3.0
dtype: float64

In [104]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [105]:
# Slicing with labels behaves differently than normal Python slicing in 
# that the endpoint is inclusive
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [106]:
# indexing dataframe
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
     index=['Ohio', 'Colorado', 'Utah', 'New York'],
     columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [107]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [108]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [109]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [110]:
data[data['three'] >= 10]

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [111]:
# Filtering
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [112]:
data[data < 5] = 0

In [113]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Selection with loc and iloc
    - select a subset of the rows and columns from a DataFrame using
    1. using either axis labels (loc) or
    2. integers (iloc).

In [114]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [115]:
data.iloc[1, [1,2]]

two      5
three    6
Name: Colorado, dtype: int32

In [116]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [117]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

### Integer Indexes

In [118]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

Working with pandas objects indexed by integers is something that often trips up
new users due to some differences with indexing semantics on built-in Python data
structures like lists and tuples. For example, you might not expect the following code
to generate an error:

In [119]:
ser[-1] # ERROR

KeyError: -1

In [120]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [121]:
ser[:1]

0    0.0
dtype: float64

In [122]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [123]:
ser.iloc[:1]

0    0.0
dtype: float64

### Arithmetic and Data Alignment

In [124]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [125]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [126]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [127]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

The internal data alignment introduces missing values in the label locations that don’t
overlap. Missing values will then propagate in further arithmetic computations.

### Arithmetic methods with fill values

In [128]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
 columns=list('abcd'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [129]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
 columns=list('abcde'))
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [130]:
df2.loc[1, 'b'] = np.nan

In [131]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [132]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [133]:
# 1 / df1 is equivalent to df1.rdiv(1)
1 / df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [134]:
df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

### Operations between DataFrame and Series

In [135]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [136]:
arr[0]

array([0., 1., 2., 3.])

In [137]:
arr-arr[0] # broadcasting

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [138]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
     columns=list('bde'),
     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [139]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [140]:
frame - series # series is broadcasted down the rows

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [141]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [142]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

If you want to instead broadcast over the columns, matching on the rows, you have to use one of the arithmetic methods. For example:

In [143]:
series3 = frame['d']

In [144]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [145]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [146]:
frame.sub(series3, axis='index') # subtract # broadcast columns

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Function Application and Mapping
- NumPy ufuncs (element-wise array methods) also work with pandas objects:

In [152]:
#frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
#     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

frame = pd.DataFrame(np.random.randint(0,100,size=(4, 3)), columns=list('bde'),
     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [153]:
frame

b   d   e
Utah    43  95  23
Ohio    98  60  56
Texas   53  13  54
Oregon  11  16  85

In [154]:
np.abs(frame)

b   d   e
Utah    43  95  23
Ohio    98  60  56
Texas   53  13  54
Oregon  11  16  85

In [155]:
f = lambda x:x.max() - x.min()

In [157]:
frame.apply(f) 
# b = 98 - 11
# d = 95 - 13
# e = 85 - 23

b    87
d    82
e    62
dtype: int64

In [159]:
frame.apply(f, axis='columns') # function is applied per row

Utah      72
Ohio      42
Texas     41
Oregon    74
dtype: int64

In [161]:
def f(x):
     return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [162]:
frame.apply(f)

b   d   e
min  11  13  23
max  98  95  85

In [163]:
# element-wise using applymap
format = lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah    43.00  95.00  23.00
Ohio    98.00  60.00  56.00
Texas   53.00  13.00  54.00
Oregon  11.00  16.00  85.00

The reason for the name applymap is that Series has a map method for applying an
element-wise function

In [164]:
frame['e'].map(format)

Utah      23.00
Ohio      56.00
Texas     54.00
Oregon    85.00
Name: e, dtype: object

### Sorting and Ranking
- sort_index = returns a new, sorted object

In [165]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [166]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [168]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
     index=['three', 'one'],
     columns=['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [169]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [171]:
frame.sort_index(axis=1) # sorts INDEX ascending by default

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [172]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [173]:
obj = pd.Series([4, 7, -3, 2])

In [174]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [175]:
# Any missing values are sorted to the end of the Series by default
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [176]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [177]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [178]:
frame.sort_values(by='b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [179]:
# To sort by multiple columns, pass a list of names:
frame.sort_values(by=['a', 'b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [181]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [182]:
obj.rank() 
# Ranking assigns ranks from one through 
# the number of valid data points in an array

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [183]:
obj.rank(method='first')
# Ranks can also be assigned according to 
# the order in which they’re observed in the data

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [184]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

### Axis Indexes with Duplicate Labels

In [186]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [187]:
obj.index.is_unique

False

In [188]:
obj['a']

a    0
a    1
dtype: int64

In [190]:
type(obj['a']) # if obj has duplicate labels, this returns a series

pandas.core.series.Series

## Summarizing and Computing Descriptive Statistics
- pandas objects are equipped with a set of common mathematical and statistical methods.
- Most of these fall into the category of 
    1. reduction methods
    2. summary statistics methods 
        - ex. sum or mean
- Compared with the similar methods found on NumPy arrays, they have **built-in handling for missing data.**

In [191]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
     [np.nan, np.nan], [0.75, -1.3]],
     index=['a', 'b', 'c', 'd'],
     columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [192]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [193]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

NA values are excluded unless the entire slice (row or column in this case) is NA. This can be disabled with the skipna option:

In [195]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [197]:
df.idxmax() # returns index of the max num

one    b
two    d
dtype: object

In [198]:
# accumukations
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [199]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [202]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [203]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### Correlation and Covariance

In [205]:
import pandas_datareader.data as web

In [210]:
#Let’s consider some DataFrames of stock prices and volumes obtained
#from Yahoo! Finance using the add-on pandas-datareader package
all_data = {ticker: web.get_data_yahoo(ticker)
for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}
all_data

{'AAPL':                   High         Low        Open       Close      Volume  \
 Date                                                                     
 2014-10-23  105.050003  103.629997  104.080002  104.830002  71074700.0   
 2014-10-24  105.489998  104.529999  105.180000  105.220001  47053900.0   
 2014-10-27  105.480003  104.699997  104.849998  105.110001  34187700.0   
 2014-10-28  106.739998  105.349998  105.400002  106.739998  48060900.0   
 2014-10-29  107.370003  106.360001  106.650002  107.339996  52687900.0   
 2014-10-30  107.349998  105.900002  106.959999  106.980003  40654800.0   
 2014-10-31  108.040001  107.209999  108.010002  108.000000  44639300.0   
 2014-11-03  110.300003  108.010002  108.220001  109.400002  52282600.0   
 2014-11-04  109.489998  107.720001  109.360001  108.599998  41574400.0   
 2014-11-05  109.300003  108.129997  109.099998  108.860001  37435900.0   
 2014-11-06  108.790001  107.800003  108.599998  108.699997  34968500.0   
 2014-11-07  109.

In [207]:
price = pd.DataFrame({ticker: data['Adj Close']
for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
for ticker, data in all_data.items()})

In [208]:
returns = price.pct_change()

In [209]:
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2019-10-16 -0.004037  0.000507 -0.006224 -0.008194
2019-10-17  0.003883  0.007583 -0.055239 -0.005128
2019-10-18  0.004803 -0.006049 -0.001266 -0.016322
2019-10-21  0.017343  0.000530 -0.011261  0.007423
2019-10-22 -0.002287 -0.002688  0.010409 -0.014881

In [211]:
returns['MSFT'].corr(returns['IBM'])

0.4857547622770841

In [212]:
returns['MSFT'].cov(returns['IBM'])

9.373066217181849e-05

In [213]:
returns.MSFT.corr(returns.IBM)

0.4857547622770841

In [214]:
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.520430  0.405388  0.572492
GOOG  0.520430  1.000000  0.412871  0.654075
IBM   0.405388  0.412871  1.000000  0.485755
MSFT  0.572492  0.654075  0.485755  1.000000

In [215]:
returns.cov()

AAPL      GOOG       IBM      MSFT
AAPL  0.000246  0.000124  0.000083  0.000133
GOOG  0.000124  0.000230  0.000082  0.000147
IBM   0.000083  0.000082  0.000170  0.000094
MSFT  0.000133  0.000147  0.000094  0.000219

In [216]:
returns.corrwith(returns.IBM)

AAPL    0.405388
GOOG    0.412871
IBM     1.000000
MSFT    0.485755
dtype: float64

In [217]:
returns.corrwith(volume)

AAPL   -0.117577
GOOG   -0.007961
IBM    -0.131030
MSFT   -0.083117
dtype: float64

### Unique Values, Value Counts, and Membership

In [234]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [235]:
uniques = obj.unique()

In [236]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [237]:
type(uniques)

numpy.ndarray

In [238]:
uniques.sort()
uniques

array(['a', 'b', 'c', 'd'], dtype=object)

In [239]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [240]:
pd.value_counts(obj.values, sort=False)

a    3
d    1
c    3
b    2
dtype: int64

In [241]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [242]:
mask = obj.isin(['b','c'])

In [243]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [244]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [247]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match)
# returns matched indices for each to_match value 
# 0 if to_match_val == c
# 1 if to_match_val == b
# 2 if to_match_val == a

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [251]:
# histogram
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
     'Qu2': [2, 3, 1, 2, 3],
     'Qu3': [1, 5, 2, 4, 4]})

In [252]:
result = data.apply(pd.value_counts).fillna(0)

In [253]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0