Book Reference: page 123-151 of **Python for Data Analysis Book by Wes McKinney**

# pandas

- contains data structures and data manipulation tools designed to make data cleaning and analysis fast and easy in Python
- Difference between pandas and numpy:
    - pandas is designed for working with tabular or heterogeneous data
    - Numpy is best suited for working with homogeneous numerical array data
- open source project in 2010

In [183]:
import pandas as pd

# or 
# from pandas import Series, DataFrame

### 2 Workhorse data structures
1. Series
    - is a one-dimensional array-like object containing a sequence of values and an associated array of data labels (index)
    - fixed-length, ordered dict
2. DataFrame
    - represents a rectangular table of data
    - contains an ordered collection of columns (which may be of different value types)
    - has both a row and column index
    - dict of Series sharing the same index

In [184]:
obj = pd.Series([1,2,3,'ha'])
obj

0     1
1     2
2     3
3    ha
dtype: object

In [185]:
obj2 = pd.Series([4, 7, -5, 3])
obj2

0    4
1    7
2   -5
3    3
dtype: int64

In [186]:
obj2.values

array([ 4,  7, -5,  3], dtype=int64)

In [187]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [188]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [189]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [190]:
# use labels in the index when selecting single values or a set of values
obj2['a']

-5

In [191]:
obj2['d'] = 6

In [192]:
obj2[['c', 'a', 'd']] #c,a,d interpreted as list of indices

c    3
a   -5
d    6
dtype: int64

Numpy-like operations
- filtering with a boolean arra
- scalar multiplication
- applying math functions

In [193]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [194]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [195]:
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [196]:
# dict-like operations
'b' in obj2

True

In [197]:
# convert Python dict to Series

sdata = {'Ohio': 35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [198]:
# override ordered index through...
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [199]:
# Check for missing or NA 
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [200]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [201]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [202]:
# Data alignment feature
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Series' object itself AND Series' index both have names


In [203]:
obj4.name = 'population'

In [204]:
obj4.index.name = 'state'

In [205]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [206]:
obj

0     1
1     2
2     3
3    ha
dtype: object

In [207]:
# Series's index can be altered in-place by assignment
obj.index = ['Jennie', 'Lisa', 'Rose', 'Jisoo']

In [208]:
obj

Jennie     1
Lisa       2
Rose       3
Jisoo     ha
dtype: object

### DataFrame

In [209]:
data = {
    'singer': ['Blackpink', 'NCT', 'Seventeen', 'SF9'],
    'year': [2018, 2017, 2019, 2017],
    'title': ['As If It\'s Your Last', 'Cherry Bomb', 'Fear', 'O Sole Mio']
}

In [210]:
frame = pd.DataFrame(data)

In [211]:
frame

singer                 title  year
0  Blackpink  As If It's Your Last  2018
1        NCT           Cherry Bomb  2017
2  Seventeen                  Fear  2019
3        SF9            O Sole Mio  2017

In [212]:
frame.head() # displays first five rows

singer                 title  year
0  Blackpink  As If It's Your Last  2018
1        NCT           Cherry Bomb  2017
2  Seventeen                  Fear  2019
3        SF9            O Sole Mio  2017

In [213]:
pd.DataFrame(data, columns=['year', 'title', 'singer'])

year                 title     singer
0  2018  As If It's Your Last  Blackpink
1  2017           Cherry Bomb        NCT
2  2019                  Fear  Seventeen
3  2017            O Sole Mio        SF9

In [214]:
frame2 = pd.DataFrame(data, columns=['year', 'title', 'singer', 'rating'], 
            index=['one', 'two', 'three', 'four'])
frame2

year                 title     singer rating
one    2018  As If It's Your Last  Blackpink    NaN
two    2017           Cherry Bomb        NCT    NaN
three  2019                  Fear  Seventeen    NaN
four   2017            O Sole Mio        SF9    NaN

In [215]:
frame2.columns

Index(['year', 'title', 'singer', 'rating'], dtype='object')

In [216]:
frame2['singer']

one      Blackpink
two            NCT
three    Seventeen
four           SF9
Name: singer, dtype: object

In [217]:
frame2.title # this only works when the column name is a valid Python variable name

one      As If It's Your Last
two               Cherry Bomb
three                    Fear
four               O Sole Mio
Name: title, dtype: object

In [218]:
frame2.loc['three'] #rows

year           2019
title          Fear
singer    Seventeen
rating          NaN
Name: three, dtype: object

Columns can be modified by assignment

In [219]:
frame2['rating'] = 3.5

In [220]:
frame2

year                 title     singer  rating
one    2018  As If It's Your Last  Blackpink     3.5
two    2017           Cherry Bomb        NCT     3.5
three  2019                  Fear  Seventeen     3.5
four   2017            O Sole Mio        SF9     3.5

In [221]:
frame2['rating'] = np.arange(4.)

In [222]:
frame2

year                 title     singer  rating
one    2018  As If It's Your Last  Blackpink     0.0
two    2017           Cherry Bomb        NCT     1.0
three  2019                  Fear  Seventeen     2.0
four   2017            O Sole Mio        SF9     3.0

In [223]:
# Series(rating_value's) length must match the length of  the DataFrame
rating_val = pd.Series([4,5], index=['two', 'four'])

In [224]:
frame2['rating'] = rating_val

In [225]:
frame2

year                 title     singer  rating
one    2018  As If It's Your Last  Blackpink     NaN
two    2017           Cherry Bomb        NCT     4.0
three  2019                  Fear  Seventeen     NaN
four   2017            O Sole Mio        SF9     5.0

In [226]:
# add new column
frame2['girl_group'] = frame2.singer == 'Blackpink'

In [227]:
frame2

year                 title     singer  rating  girl_group
one    2018  As If It's Your Last  Blackpink     NaN        True
two    2017           Cherry Bomb        NCT     4.0       False
three  2019                  Fear  Seventeen     NaN       False
four   2017            O Sole Mio        SF9     5.0       False

In [228]:
# delete column
del frame2['girl_group']

In [229]:
frame2

year                 title     singer  rating
one    2018  As If It's Your Last  Blackpink     NaN
two    2017           Cherry Bomb        NCT     4.0
three  2019                  Fear  Seventeen     NaN
four   2017            O Sole Mio        SF9     5.0

In [230]:
frame2.columns

Index(['year', 'title', 'singer', 'rating'], dtype='object')

The column returned from indexing a DataFrame is a view on the
underlying data, not a copy. Thus, any in-place modifications to the
Series will be reflected in the DataFrame. The column can be
explicitly copied with the Series’s **copy method**.

In [231]:
# nested dict of dicts
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [232]:
frame3 = pd.DataFrame(pop)

In [233]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [234]:
frame3.T # transpose

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [235]:
frame3['Ohio'][:-1]

2000    1.5
2001    1.7
Name: Ohio, dtype: float64

In [236]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [237]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [344]:
frame2.values # see how dtype is object

array([[ 0.,  1.,  2.],
       [nan, nan, nan],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

### Index Objects
    - responsible for holding the axis labels and other metadata
    - immutable
    - fixed-size set
    - can contain duplicate labels

In [345]:
obj = pd.Series(range(3), index=['a','b','c'])
obj

a    0
b    1
c    2
dtype: int64

In [346]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [347]:
index[1:]

Index(['b', 'c'], dtype='object')

In [348]:
# immutable index
index[1] = 'd'

TypeError: Index does not support mutable operations

In [ ]:
labels = pd.Index(np.arange(3))

In [ ]:
labels

In [ ]:
# Immutability makes it safer to share Index objects among data structures
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [ ]:
obj2

In [ ]:
obj2.index is labels

In [ ]:
frame3

In [349]:
frame3

state  the nevada  Ohio
year                   
2000          NaN   1.5
2001          2.4   1.7
2002          2.9   3.6

In [350]:
frame3.columns

Index(['the nevada', 'Ohio'], dtype='object', name='state')

In [351]:
# duplicate labels
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [352]:
# rename index/column through rename func
frame3.rename(columns={'Nevada':'the nevada'}, inplace=True)

In [353]:
frame3.columns

Index(['the nevada', 'Ohio'], dtype='object', name='state')

### Reindexing
    -An important method on pandas objects is reindex, which means to create a new object with the data conformed to a new index.

In [354]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [355]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [356]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [357]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

For ordered data like **time series**, it may be desirable to do some **interpolation or filling of values** when reindexing. The method option allows us to do this, using a method such as ffill, which forward-fills the values

In [358]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [359]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [360]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

With DataFrame, reindex can alter either the (row) index, columns, or both. When
passed only a sequence, it reindexes the rows in the result:

In [361]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
     index=['a', 'c', 'd'],
     columns=['Ohio', 'Texas', 'California'])

In [362]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [363]:
# reindex rows
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [364]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [365]:
# reindex columns
states = ['Texas', 'Utah', 'California']
frame.reindex(columns= states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [377]:
frame.reindex(index=['a', 'b', 'c', 'd'], columns=states)
# see more reindex function arguments to customize

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [378]:
frame2.columns

Index(['Ohio', 'Texas', 'California'], dtype='object')

In [380]:
frame.reindex(columns=['Texas','Utah','California'], fill_value=0)

Texas  Utah  California
a      1     0           2
c      4     0           5
d      7     0           8

In [369]:
# Dropping Entries from an Axis

In [370]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [371]:
new_obj = obj.drop('c')

In [372]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [373]:
obj.drop(['d', 'c']) 
# drop method will return a new object with the 
# indicated value or values deleted from an axis:

a    0.0
b    1.0
e    4.0
dtype: float64

In [374]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
     index=['Ohio', 'Colorado', 'Utah', 'New York'],
     columns=['one', 'two', 'three', 'four'])

In [375]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [376]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [286]:
# drop values from the columns by passing axis=1 or axis='columns':
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [287]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [288]:
# You can also choose to modify the size or shape of a Series or DataFrame using
# in-place

obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

Be careful with the inplace, as it <span style="color:red">destroys any data that is dropped. </span>

### Indexing, Selection, and Filtering

In [289]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [290]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [291]:
obj['b']

1.0

In [292]:
obj[1]

1.0

In [293]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [295]:
obj['b':'d']

b    1.0
c    2.0
d    3.0
dtype: float64

In [296]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [297]:
# Slicing with labels behaves differently than normal Python slicing in 
# that the endpoint is inclusive
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [299]:
# indexing dataframe
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
     index=['Ohio', 'Colorado', 'Utah', 'New York'],
     columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [300]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [301]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [302]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [305]:
data[data['three'] >= 10]

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [308]:
# Filtering
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [314]:
data[data < 5] = 0

In [315]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Selection with loc and iloc
    - select a subset of the rows and columns from a DataFrame using
    1. using either axis labels (loc) or
    2. integers (iloc).

In [316]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [318]:
data.iloc[1, [1,2]]

two      5
three    6
Name: Colorado, dtype: int32

In [319]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [320]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

### Integer Indexes

In [323]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

Working with pandas objects indexed by integers is something that often trips up
new users due to some differences with indexing semantics on built-in Python data
structures like lists and tuples. For example, you might not expect the following code
to generate an error:

In [325]:
ser[-1] # ERROR

KeyError: -1

In [326]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [327]:
ser[:1]

0    0.0
dtype: float64

In [328]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [329]:
ser.iloc[:1]

0    0.0
dtype: float64

### Arithmetic and Data Alignment

In [330]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [331]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [332]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [333]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

The internal data alignment introduces missing values in the label locations that don’t
overlap. Missing values will then propagate in further arithmetic computations.

### Arithmetic methods with fill values

In [337]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
 columns=list('abcd'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [336]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
 columns=list('abcde'))
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [338]:
df2.loc[1, 'b'] = np.nan

In [339]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [340]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [341]:
# 1 / df1 is equivalent to df1.rdiv(1)
1 / df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [381]:
df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

### Operations between DataFrame and Series

In [382]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [383]:
arr[0]

array([0., 1., 2., 3.])

In [385]:
arr-arr[0] # broadcasting

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [387]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
     columns=list('bde'),
     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [388]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [390]:
frame - series # series is broadcasted down the rows

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [392]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [393]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

If you want to instead broadcast over the columns, matching on the rows, you have to use one of the arithmetic methods. For example:

In [394]:
series3 = frame['d']

In [395]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [396]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [399]:
frame.sub(series3, axis='index') # subtract # broadcast columns

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Function Application and Mapping
- NumPy ufuncs (element-wise array methods) also work with pandas objects: